chatServer:
  image: ghcr.io/sipixer/server-chat/chat-server:main-858b73e65fb456b9f74ac9fa5e6e913b57c075f3
  replicas: 1
  port: 3000

redis:
  image: redis:8.2.2-alpine
  replicas: 1
  port: 6379
  storage:
    size: 1Gi
    storageClass: hcloud-volumes

ingress:
  host: sylvain-chat.duckdns.org
  className: traefik
